### ISSUE TITLE
Prendre une photo avec l'appreil photo du tel mobile

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/app#45]
Ajouter un bouton <Prendre Photo> & pouvoir afficher cette Photo

**Comment by bioboosterbob** [comment]
Notre bouton prend bien la photo.
celle ci est memorisé  dans pesto via 
```
const [photoImage, setPhotoImage] = useState<CameraCapturedPicture>
``` 
elle est enregistrée automatiquement par android (sera presente dans votre gallerie) & nous y accedons via 
```
photoImage.uri  
````

rendu de la preview sommaire via PestoCard, il faudra rechargez l'app pour vider photoImage pour l'instant

**Comment by Jean-Baptiste-Lasselle** [comment]
ok super le bouton take picture et preview photo: 


du coup maintenant il reste à faire le fait de sauvegarder la photo dans la gallerie

**Comment by bioboosterbob** [comment]
donc tu as ta branche et ta mission est d'arriver à erennregistrer la phot dans la gallerie dans el télphone : après avoir kill l'app mobile sur android, on retrouve les photos dansles fivhoiers

et du coup je travaille sur ça :  https://github.com/3forges/app/issues/46

**Comment by bioboosterbob** [comment]
et quand c'est fait on vreut la meêm chose en prenant une vidéo

**Comment by bioboosterbob** [comment]
pour aujourd'hui, on est bon avec l'enregistrement video, le bouton video switch bien (start/stop) & est correctement reset si maxSize ou maxDuration as été defini.

la preview fourni un player avec ses control & demarre la video
on pourra soit discard la video soit la save 

/!\ CONCERNANT LA SAVE: j'ai passé MediaLibrary.addAssetsToAlbumAsync( ..., ..., false) pour faire une copie dans la galerie Pesto, sinon l'App plante, nous laissant avec la modale android de permission.

j'ai beaucoup chercher, je ne vois pas, les mediaType [audio|image|...] se declarent uniquement pour la lecture, MediaLibrary.addAssetsToAlbumAsync gere image ET video.
aucuns messages evidement coté console shell server ...

**Comment by bioboosterbob** [comment]
en rab un slider effectif, horizontal, mais effectif

**Comment by bioboosterbob** [comment]
ok prendrfe une vidéo est possible, mais on a un crash qd on utilise l'option : 

```tsx
MediaLibrary.addAssetsToAlbumAsync(videoAsset, pestoAlbum, false) // false = move | true = copy
```

Refs : 
* recherche google : `crash expo android app  MediaLibrary.addAssetsToAlbumAsync   copy otions false`
* https://github.com/expo/expo/issues/13200#issuecomment-904611915
*

**Comment by bioboosterbob** [comment]
pour palier au bug MediaLibrary.addAssetsToAlbumAsync sur une video:
* je vais installer expo/filesystem 
* je vais faire deplacer le fichier dans picture.uri vers le repertoire gallerie Pesto par l'app.

=> a voir, le maintiens ou non de MediaLibrary ou non dans le composant PestoCamera, ou sont decalage dans un composant ~PestoGaleryBrowser,  en cas de succes

**Comment by bioboosterbob** [comment]
correction bug permission MediaLibrary (plus besoin du context comme on pensais)

PestoCamera L. 272
``` 
<Button onPress={ async () => { 
              await requestMediaLibraryPermissionResponse
              setMediaLibraryPermissionResponseState(mediaLibraryPermissionResponse)
              console.log("BOUTON GRANT PERMISSION GALLERY PHOTO :", mediaLibraryPermissionResponse)
            }} 
            title="grant permission" />
``` 

to

``` 
<Button onPress={ async () => { 
              setMediaLibraryPermissionResponseState(await requestMediaLibraryPermissionResponse) 
              console.log("BOUTON GRANT PERMISSION GALLERY PHOTO :", mediaLibraryPermissionResponse)
            }} 
            title="grant permission" />
```

**Comment by bioboosterbob** [comment]
nouveau: MediaLibrary.addAssetsToAlbumAsync(photoAsset, pestoPhotoAlbum, **true**) ne fait plus planter expo.

par contre que l'on passe l'argument copy a true ou false, la photo sera presente dans la galerie Pesto & DCIM.
C'est assez mal-aisant, peut etre devrions nous repasser quelqes test afin de cultiver quelques certitudes.

* ca semble confus, qu'une permission camera roll, certe issue de MediaLibray permission (really ??) stabilise la fonction MediaLibrary.addAssetsToAlbumAsync
* le "changement de contexte" -modif ExpoConfig.slug influ t'il lui seul sur ce changement de comportement ??

**Comment by bioboosterbob** [comment]
[MediaLibrary.createAssetAsync(localUri)](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibrarycreateassetasynclocaluri)

"Creates an asset from existing file. The most common use case is to save a picture taken by [Camera](https://docs.expo.dev/versions/latest/sdk/camera/). **This method requires CAMERA_ROLL permission.**"


[MediaLibrary.addAssetsToAlbumAsync(assets, album, copy)](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibraryaddassetstoalbumasyncassets-album-copy)

"On Android, by default it copies assets from the current album to provided one, however it's also possible to move them by passing false as copyAssets argument.**In case they're copied you should keep in mind that getAssetsAsync will return duplicated assets**."

**Comment by Jean-Baptiste-Lasselle** [comment]
> [MediaLibrary.createAssetAsync(localUri)](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibrarycreateassetasynclocaluri)
> 
> "Creates an asset from existing file. The most common use case is to save a picture taken by [Camera](https://docs.expo.dev/versions/latest/sdk/camera/). **This method requires CAMERA_ROLL permission.**"
> 
> [MediaLibrary.addAssetsToAlbumAsync(assets, album, copy)](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibraryaddassetstoalbumasyncassets-album-copy)
> 
> "On Android, by default it copies assets from the current album to provided one, however it's also possible to move them by passing false as copyAssets argument.**In case they're copied you should keep in mind that getAssetsAsync will return duplicated assets**."

YEAAAAAAAAAAAAAAAAAAAAAAAAA mais bon sang masi c'est bien sûr ! ^^

**Comment by bioboosterbob** [comment]
Avec les permissions rectifiés, je propose MediaLibrary.deleteAssetsAsync() pour simplement effacer le doublon lors de la sauvergade d'une vidéo.

c'est fonctionnel & pushed, a peine une modification de code dans PestoCamera.tsx, juste le changment de slug dans app.config.ts.

Je vais continuer quand meme de fouiller ces permissions, l'app continue de d'appeler une popup android a chaque enregistrement, ce qui n'arrivait plus je crois, mais G un doute là.

de toutes facons il faudra pouvoir gerer ses perms, genre dans un onglet paramatres à termes

**Comment by bioboosterbob** [comment]
resumé de la situation des permissions:

1 code nous sert les permissions sans demander les permissions roll & fait planter expo
1 autre code sert les permissions en demandant celle concernant roll (Camera) mais oublie les permission& fait pop les perm android, ne fait pas planter l'app & fonctionneadequatement dans la gallerie

**Comment by bioboosterbob** [comment]
l'issue est resolue sur ce commit b7c00ef8d9654486f5c01c2c500aff334795c50b
