### ISSUE TITLE
Store and Navigation

### ISSUE THREAD

**Issue by bioboosterbob** [3forges/app#8]
Cette tache consiste à resoudre ce problème avec la technologie redux

## Linked PR

https://github.com/3forges/app/pull/13

## reproduire le bug :

* cloner le repo, et lancer l'app:
```bash
git clone git@github.com:3forges/app.git
cd app
git checkout 443399ed4c3437ca7ab9fad4be9fe95e59504365
yarn && npm run web
```

* ajouter quelques utilisateurs : 

![image](https://github.com/3forges/app/assets/89749441/f521937e-8c9b-42cb-9381-155f99a95381)
![image](https://github.com/3forges/app/assets/89749441/743fc478-eed5-43e7-a414-05871e632658)

* clicker sur l'icone d'edition d'un profil (icone avec le stylo) :
![image](https://github.com/3forges/app/assets/89749441/7a90fc4e-8387-4396-8e0a-8ce949a0d2cc)

![image](https://github.com/3forges/app/assets/89749441/036e98e4-40d0-4ac6-80fa-c992b1c14fed)

* Arrivé sur cette page, revenez sur la page d'accueil en appuyant sur **back**
![image](https://github.com/3forges/app/assets/89749441/447194ec-6c0f-4843-a024-509e25c191c3)

les utilisateur crées précédement ont disparus : 
![image](https://github.com/3forges/app/assets/89749441/75ad5c39-4ba1-4830-a5ce-6c375fdb181c)

**Comment by Jean-Baptiste-Lasselle** [comment]
regardes : 
* premier
* un autre
* et le troisième

**Comment by Jean-Baptiste-Lasselle** [comment]
et encore : 
* je te parle de cuisine : 
  *  et ça
  * c'est une sous liste
  * d'ailleurs, je ne dois pas oublier de : 
    * [ ] créer une autre tâche pour m'entraîner à utiliser les outils github
    * [ ] faire telle autre chose
    * [ ] et me faire un bon petit repas bien français
* je te parle de mécanique: 
  * des fluildes

**Comment by bioboosterbob** [comment]
# super !
* blabla
* lmdsf, :

**Comment by bioboosterbob** [comment]
1er tuto fonctionnel : 
https://dev.to/theadultnoble_6/how-to-use-redux-toolkit-with-react-native-2dm5

**Comment by bioboosterbob** [comment]
https://redux-toolkit.js.org/tutorials/typescript

**Comment by bioboosterbob** [comment]
https://github.com/3forges/app/pull/13

**Comment by bioboosterbob** [comment]
Redux fonctionnel ce matin, cependant cela nous ammene a repenser notre logique :

![Image](https://github.com/3forges/app/assets/89749441/1dc93f7d-0229-48e1-92a0-86aa10d3c368)


qui plus est, redux accepte mal le passage de fonction via PestoUser props: onClick: Function

```bash
export interface PestoUser {
  name: string;
  picture: string;
  index?: number;
  onClick?: Function;
}
```



![Image](https://github.com/3forges/app/assets/89749441/2a7c25f1-d4d7-4728-83b1-75cb9a9f9bb3)

Objectif: supprimer les props onClick des composant,s pour fonctionner dans un context unique

**Comment by Jean-Baptiste-Lasselle** [comment]
@bioboosterbob petit changement pour simplifier / découper le tâches :

de toute façon, ce soir on regarde à nouveau ensemble ton code pour voir comment simplifier et virer tout ce qui ne sert à rien dans ton code : 

si avec thunk l'appel à random user c'est trop compliqué : et ja'ai l'impression c'est trop compliqué, là tu m'as parlé de modale, bref ça part en cacahuète la UI juste à cuse de redux

alors on va faire autre chose : tu vas changer ton code pour oublier randomusers
et à la place de random users, je veux juste saisir le nom du user, avec un seul champ, et que ça ajoute ce user dans la liste. Sans aire aucune requête réseau

**Comment by bioboosterbob** [comment]
updated & pushed.

pour le moment j'ai laissé le message d'erreur de serialisation (onClick: Function):
![Image](https://github.com/3forges/app/assets/89749441/2a7c25f1-d4d7-4728-83b1-75cb9a9f9bb3)
comme je disait , la logique de navigation/store doit etre remanié, donc peut etre apres le merge avec ta navigation

**Comment by Jean-Baptiste-Lasselle** [comment]
solved by merging #13
